FROM node:20.10.0 AS build

WORKDIR /app

# Copy and install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy all backend files
COPY backend/ ./

# 👇 Explicitly copy .env
COPY backend/.env .env

# Set environment variable for production
ENV NODE_ENV=production

EXPOSE 5000

CMD ["nodemon", "index.js"]
